name: lifehash
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.lifehash
        pluginClass: LifehashPlugin
      ios:
        pluginClass: LifehashPlugin
