name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Dart SDK version
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

    
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test
